stages:
  fetch_data_from_gcs:
    cmd: python src/dataset.py
    deps:
      - src/dataset.py
    outs:
      - data/raw/california-housing.csv

  preprocess:
    cmd: python src/features.py
    deps:
      - src/features.py
      - src/config.py
      - params.yaml
      - data/raw/california-housing.csv
    outs:
      - data/processed
      - artifacts/preprocessor

  train:
    cmd: python src/modeling/train.py
    deps:
      - src/modeling/train.py
      - data/processed
    outs:
      - artifacts/model
